{% set name = "igor2" %}
{% set version = "0.5.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 14e5d4223dc8556cf13d03416fca35ded4b83c9c48a5d050ea9b4e5a1283033a

build:
  entry_points:
    - igorbinarywave = igor2.cli.igorbinarywave:main
    - igorpackedexperiment = igor2.cli.igorpackedexperiment:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.6,<4
    - setuptools >=45
    - setuptools-scm >=6.2
    - pip
  run:
    - python >=3.6,<4
    - numpy >=1.19.2

test:
  imports:
    - igor2
  commands:
    - pip check
    - igorbinarywave --help
    - igorpackedexperiment --help
  requires:
    - pip

about:
  home: https://github.com/AFM-analysis/igor2
  summary: Interface for reading binary IGOR files
  description: |
    Python parser for IGOR Binary Waves (.ibw) and Packed Experiment (.pxp)
    files written by WaveMetrics' IGOR Pro software. igor2 is the continuation
    of the inactive igor project.
  license: LGPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - janberges
