{% set name = "igor2" %}
{% set version = "0.5.12" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 5a284ac3b7aa6a8a59f28509d06359ea29e08d6f9f563566d2a0f15ea9681893

build:
  entry_points:
    - igorbinarywave = igor2.cli.igorbinarywave:main
    - igorpackedexperiment = igor2.cli.igorpackedexperiment:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=45
    - setuptools-scm >=6.2
    - pip
  run:
    - python >={{ python_min }},<4
    - numpy >=1.19.2

test:
  imports:
    - igor2
  commands:
    - pip check
    - igorbinarywave --help
    - igorpackedexperiment --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/AFM-analysis/igor2
  summary: Interface for reading binary IGOR files
  description: |
    Python parser for IGOR Binary Waves (.ibw) and Packed Experiment (.pxp)
    files written by WaveMetrics' IGOR Pro software. igor2 is the continuation
    of the inactive igor project.
  license: LGPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - janberges
